<?php


/** @var \Magento\Sales\Block\Adminhtml\Order\View\Info $block */
?>
<?php if ($comment = $block->getOrderComment()) :?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @escapeNotVerified */ \__('Order Comment') ?></span>
        </div>
        <div class="admin__page-section-content">
            <?= \nl2br($block->escapeHtml($comment));?>
        </div>
    </section>
<?php endif; ?>
