<?php $order = $block->getOrder() ?>

<td class="label"><?= /* @escapeNotVerified */ \__('Handling Fee') ?><div id="handling_fee"></div></td>
<td>
    <input type="text"
           name="creditmemo[handling_fee]"
           value="<?= (float)$order->getHandlingFee() - (float)$order->getRefundedHandlingFee() ?>"
           class="input-text admin__control-text not-negative-amount"
           id="handling_fee" />
</td>
