<?php
$paymentMethods = $this->getPaymentMethods();
?>

<?php if ($paymentMethods && count($paymentMethods) > 0): ?>
    <form id="maksuturva_part_payment_payment-form" class="form form-purchase-order" data-role="maksuturva_part_payment_payment-form">
            <?php $_code = $this->getMethodCode() ?>
            <div id="payment_form_<?php echo $_code ?>" style="display:inline-flex;">

                <?php foreach ($paymentMethods as $method): ?>
                    <div class="payment-method">
                        <label for="maksuturva_part_payment_<?php echo $method->code ?>">
                            <img src="<?php echo $method->imageurl ?>" alt="<?php echo $method->displayname ?>"/>
                        </label>
                        <div class="input-wrapper" style="margin-left: 50%;">
                            <input type="radio" class="radio maksuturva_part_payment_-radio" id="maksuturva_part_payment_<?php echo $method->code ?>"
                                   name="payment[maksuturva_part_payment_preselected_payment_method]"
                                   value="<?php echo $method->code ?>"
                                   onclick="selectPaymentMethod(this.value)"
                                   data-validate="{required:true}">
                        </div>
                    </div>
                <?php endforeach ?>

            </div>
        </fieldset>
    </form>
    <script>
        require(['jquery', "mage/mage"], function($) {
            "use strict";
            if(window.checkoutConfig.payment.maksuturva_part_payment_payment.preselected_payment_method){
                $("#maksuturva_part_payment_" + window.checkoutConfig.payment.maksuturva_part_payment_payment.preselected_payment_method).prop('checked', true);
            }else{
                $('.maksuturva_part_payment-radio').first().prop('checked', true);
                window.checkoutConfig.payment.maksuturva_part_payment_payment.preselected_payment_method = $('.maksuturva_part_payment-radio').first().val();
            }
        });

        function selectPaymentMethod(value){
            window.checkoutConfig.payment.maksuturva_part_payment_payment.preselected_payment_method = value;
        }
    </script>
<?php endif ?>

