<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if ($block->isPossibleOnepageCheckout()):?>
    <?php $buttonImageUrl = $this->getMasterpassImageUrl(); ?>
    <?php if($block->isMasterpassEnabled()): ?>
        <div class="summary-masterpass">
            <div data-bind="i18n: 'Make instant payment'"></div>
            <a href="#"
               data-role="proceed-to-checkout"
               title="<?= /* @escapeNotVerified */ __('Masterpass Checkout') ?>"
               data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?php /* @escapeNotVerified */ if ($block->isDisabled()){echo '#'; }else{echo $block->getNewMasterpassUrl();} ?>"}}'>
                <img src="<?php echo $buttonImageUrl;?>" />
            </a>
            <a href="https://www.mastercard.com/mc_us/wallet/learnmore/fi/FI/" target="_blank" data-bind="i18n: 'Read more...'"></a>
        </div>
    <?php endif; ?>

    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <span><?= /* @escapeNotVerified */ __('Proceed to Checkout') ?></span>
    </button>
<?php endif; ?>
